[build-system]
requires = [
  "hatchling",
  "hatch-vcs",
]
build-backend = "hatchling.build"

[project]
name = "datalad-core"
dynamic = ["version"]
description = 'core library for the datalad-framework'
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = [
  "datalad",
  "git",
  "git-annex",
]
authors = [
  { name = "Michael Hanke", email = "michael.hanke@gmail.com" },
]
maintainers = [
  { name = "Michael Hanke", email = "michael.hanke@gmail.com" },
]
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/datalad/datalad-core"
Documentation = "https://github.com/datalad/datalad-core#readme"
Issues = "https://github.com/datalad/datalad-core/issues"
Source = "https://github.com/datalad/datalad-core"
Changelog = "https://github.com/datalad/datalad-core/blob/main/CHANGELOG.md"

[tool.hatch.version]
source = "vcs"

[tool.hatch.envs.hatch-test]
default-args = ["datalad_core"]
extra-dependencies = [
  "pytest",
  # if you come here, because coverage combination crashed for you
  # run `hatch test --cover` and/or see
  # https://github.com/pypa/hatch/issues/1565#issuecomment-2163773123
  "pytest-cov",
]
[tool.hatch.envs.docs]
extra-dependencies = [
  "sphinx",
]
[tool.hatch.envs.docs.scripts]
build = [
  "make -C docs html",
]
clean = [
  "rm -rf docs/generated",
  "make -C docs clean",
]


[tool.coverage.run]
source_pkgs = ["datalad_core", "tests"]
branch = true
parallel = true
omit = [
#  "src/datalad_core/__about__.py",
]
data_file = "${COVERAGE_ROOT-.}/.coverage"

[tool.coverage.paths]
datalad_core = ["src/datalad_core", "*/datalad_core/src/datalad_core"]
tests = ["tests", "*/datalad_core/tests"]

[tool.coverage.report]
show_missing = true
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "raise NotImplementedError",
]

